import * as fs from 'fs';
import * as path from 'path';
import * as readline from 'readline/promises';
import { loadGraph } from '../lib/graph';
import { computePlan, PlanGroup, PlanResult } from '../lib/plan';
import { GraphNode } from '../lib/types';

export interface PlanOptions {
  epic?: string;
  output?: string;
  force?: boolean;
  json?: boolean;
}

const REASON_NOTES: Record<string, string> = {
  cycle: 'grouped — circular depends_on relationship; build together or review the modeling',
  dispatch: 'grouped — connected via a dispatches edge; build together',
  'cycle+dispatch': 'grouped — circular depends_on relationship and a dispatches edge; build together or review the modeling',
};

export async function planCommand(options: PlanOptions): Promise<void> {
  const root = process.cwd();

  let graph;
  try {
    graph = loadGraph(root);
  } catch (err: any) {
    console.log(`Could not read traverspec/graph.yaml: ${err.message}`);
    process.exitCode = 1;
    return;
  }

  let epicId: string | undefined;
  if (options.epic) {
    epicId = options.epic.startsWith('epic:') ? options.epic : `epic:${options.epic}`;
    if (!graph.epics.some((e) => e.id === epicId)) {
      console.log(`No epic '${epicId}' found in traverspec/graph.yaml. Known epics: ${graph.epics.map((e) => e.id).join(', ') || '(none)'}`);
      process.exitCode = 1;
      return;
    }
  }

  const result = computePlan(graph);
  const nodesById = new Map<string, GraphNode>(graph.nodes.map((n) => [n.id, n]));
  const filtered = epicId ? filterByEpic(result, nodesById, epicId) : result;

  if (options.json) {
    console.log(JSON.stringify(filtered, null, 2));
    return;
  }

  const markdown = formatMarkdown(filtered, nodesById, epicId);
  const plansDir = path.join(root, 'traverspec', 'plans');
  const filename = `${options.output ?? (epicId ? `wave-plan-${epicId.replace('epic:', '')}` : 'wave-plan')}.md`;
  const targetPath = path.join(plansDir, filename);

  if (fs.existsSync(targetPath) && !options.force) {
    const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
    const answer = (await rl.question(`${path.relative(root, targetPath)} already exists — overwrite? [y/N] `))
      .trim()
      .toLowerCase();
    rl.close();
    if (answer !== 'y' && answer !== 'yes') {
      console.log('Aborted — nothing was written. Use --output <name> to save under a different name instead.');
      return;
    }
  }

  fs.mkdirSync(plansDir, { recursive: true });
  fs.writeFileSync(targetPath, markdown);
  console.log(`Wrote ${path.relative(root, targetPath)}`);
}

function filterByEpic(result: PlanResult, nodesById: Map<string, GraphNode>, epicId: string): PlanResult {
  const inEpic = (id: string) => nodesById.get(id)?.epic === epicId;

  const waves = result.waves
    .map((wave) => ({
      waveNumber: wave.waveNumber,
      groups: wave.groups.filter((g) => g.members.some(inEpic)),
    }))
    .filter((wave) => wave.groups.length > 0);

  return { waves };
}

function formatMarkdown(result: PlanResult, nodesById: Map<string, GraphNode>, epicId?: string): string {
  const lines: string[] = [];
  lines.push(`# Wave Plan — ${epicId ?? 'Full Graph'}`);
  lines.push('');
  lines.push(`Generated by \`traverspec plan\` on ${new Date().toISOString().slice(0, 10)}.`);
  lines.push('');

  if (result.waves.length === 0) {
    lines.push('No features found to plan.');
    return lines.join('\n') + '\n';
  }

  for (const wave of result.waves) {
    lines.push(`## Wave ${wave.waveNumber}`);
    lines.push('');
    for (const group of wave.groups) {
      lines.push(formatGroupLine(group, nodesById, epicId));
    }
    lines.push('');
  }

  return lines.join('\n').trimEnd() + '\n';
}

function formatGroupLine(group: PlanGroup, nodesById: Map<string, GraphNode>, epicId?: string): string {
  const memberLabels = group.members.map((id) => {
    const node = nodesById.get(id);
    const isExternal = epicId && node?.epic !== epicId;
    return isExternal ? `${id} (external: ${node?.epic ?? 'no epic'})` : id;
  });

  if (group.reason === 'single') {
    return `- ${memberLabels[0]}`;
  }

  const note = REASON_NOTES[group.reason] ?? group.reason;
  return `- ${memberLabels.join(', ')} (${note})`;
}
